name: Import Devices
on:
  issues:
    types:
      - opened

jobs:
  import_devices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install -r requirements.txt

      - name: Extract CSV URL
        id: csv_url
        run: |
          echo "Issue body: '${{ github.event.issue.body }}'"
          echo "Extracting CSV URL from issue body..."
          CSV_URL=$(echo '${{ github.event.issue.body }}' | grep -oP 'http[s]?://[^)]+.csv')
          echo "CSV URL: $CSV_URL"
          echo "::set-output name=url::$CSV_URL"

      - name: Download CSV
        run: |
          echo "Downloading CSV file..."
          curl -o to_process/data.csv '${{ steps.csv_url.outputs.url }}'
          echo "CSV file downloaded."

      - name: Print location and folder contents
        run: |
          echo "Current location: $PWD"
          echo "Folder contents:"
          ls -la
          echo "Data folder contents:"
          ls -la to_process
          echo "Printing CSV file contents..."
          cat to_process/data.csv

      - name: Import devices
        run: |
          echo "Importing devices from CSV file..."
          python script/process.py
          echo "Devices imported."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Import devices from issue #${{ github.event.issue.number }}"
          title: "Import devices from issue #${{ github.event.issue.number }}"
          body: "This pull request imports devices from a CSV file linked in issue #${{ github.event.issue.number }}."
          branch: "import-devices-${{ github.event.issue.number }}"
          base: "main"
